// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ex_pb/ex.proto

package grpcexample

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CalculateRequest_Operator int32

const (
	CalculateRequest_PLUS  CalculateRequest_Operator = 0
	CalculateRequest_MINUS CalculateRequest_Operator = 1
	CalculateRequest_MUL   CalculateRequest_Operator = 2
	CalculateRequest_DIV   CalculateRequest_Operator = 3
)

var CalculateRequest_Operator_name = map[int32]string{
	0: "PLUS",
	1: "MINUS",
	2: "MUL",
	3: "DIV",
}

var CalculateRequest_Operator_value = map[string]int32{
	"PLUS":  0,
	"MINUS": 1,
	"MUL":   2,
	"DIV":   3,
}

func (x CalculateRequest_Operator) String() string {
	return proto.EnumName(CalculateRequest_Operator_name, int32(x))
}

func (CalculateRequest_Operator) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ee0b8fde9a872ff2, []int{2, 0}
}

//  message의 각 필드에는 번호가 할당.
//이 필드 번호는 Message가 이진 형식으로
//직렬화 될때 필드를 식별하는데 사용.
type HiRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HiRequest) Reset()         { *m = HiRequest{} }
func (m *HiRequest) String() string { return proto.CompactTextString(m) }
func (*HiRequest) ProtoMessage()    {}
func (*HiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee0b8fde9a872ff2, []int{0}
}

func (m *HiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HiRequest.Unmarshal(m, b)
}
func (m *HiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HiRequest.Marshal(b, m, deterministic)
}
func (m *HiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HiRequest.Merge(m, src)
}
func (m *HiRequest) XXX_Size() int {
	return xxx_messageInfo_HiRequest.Size(m)
}
func (m *HiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HiRequest proto.InternalMessageInfo

func (m *HiRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HiReply struct {
	Messge               string   `protobuf:"bytes,1,opt,name=messge,proto3" json:"messge,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HiReply) Reset()         { *m = HiReply{} }
func (m *HiReply) String() string { return proto.CompactTextString(m) }
func (*HiReply) ProtoMessage()    {}
func (*HiReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee0b8fde9a872ff2, []int{1}
}

func (m *HiReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HiReply.Unmarshal(m, b)
}
func (m *HiReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HiReply.Marshal(b, m, deterministic)
}
func (m *HiReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HiReply.Merge(m, src)
}
func (m *HiReply) XXX_Size() int {
	return xxx_messageInfo_HiReply.Size(m)
}
func (m *HiReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HiReply.DiscardUnknown(m)
}

var xxx_messageInfo_HiReply proto.InternalMessageInfo

func (m *HiReply) GetMessge() string {
	if m != nil {
		return m.Messge
	}
	return ""
}

type CalculateRequest struct {
	Numbers              []int64                   `protobuf:"varint,1,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	Operator             CalculateRequest_Operator `protobuf:"varint,2,opt,name=operator,proto3,enum=grpcexample.CalculateRequest_Operator" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *CalculateRequest) Reset()         { *m = CalculateRequest{} }
func (m *CalculateRequest) String() string { return proto.CompactTextString(m) }
func (*CalculateRequest) ProtoMessage()    {}
func (*CalculateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee0b8fde9a872ff2, []int{2}
}

func (m *CalculateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculateRequest.Unmarshal(m, b)
}
func (m *CalculateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculateRequest.Marshal(b, m, deterministic)
}
func (m *CalculateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculateRequest.Merge(m, src)
}
func (m *CalculateRequest) XXX_Size() int {
	return xxx_messageInfo_CalculateRequest.Size(m)
}
func (m *CalculateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CalculateRequest proto.InternalMessageInfo

func (m *CalculateRequest) GetNumbers() []int64 {
	if m != nil {
		return m.Numbers
	}
	return nil
}

func (m *CalculateRequest) GetOperator() CalculateRequest_Operator {
	if m != nil {
		return m.Operator
	}
	return CalculateRequest_PLUS
}

type CalculateResponse struct {
	Result               int64    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculateResponse) Reset()         { *m = CalculateResponse{} }
func (m *CalculateResponse) String() string { return proto.CompactTextString(m) }
func (*CalculateResponse) ProtoMessage()    {}
func (*CalculateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee0b8fde9a872ff2, []int{3}
}

func (m *CalculateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculateResponse.Unmarshal(m, b)
}
func (m *CalculateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculateResponse.Marshal(b, m, deterministic)
}
func (m *CalculateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculateResponse.Merge(m, src)
}
func (m *CalculateResponse) XXX_Size() int {
	return xxx_messageInfo_CalculateResponse.Size(m)
}
func (m *CalculateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CalculateResponse proto.InternalMessageInfo

func (m *CalculateResponse) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterEnum("grpcexample.CalculateRequest_Operator", CalculateRequest_Operator_name, CalculateRequest_Operator_value)
	proto.RegisterType((*HiRequest)(nil), "grpcexample.HiRequest")
	proto.RegisterType((*HiReply)(nil), "grpcexample.HiReply")
	proto.RegisterType((*CalculateRequest)(nil), "grpcexample.CalculateRequest")
	proto.RegisterType((*CalculateResponse)(nil), "grpcexample.CalculateResponse")
}

func init() { proto.RegisterFile("ex_pb/ex.proto", fileDescriptor_ee0b8fde9a872ff2) }

var fileDescriptor_ee0b8fde9a872ff2 = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x14, 0xec, 0x36, 0xfd, 0xca, 0x13, 0x4a, 0x5c, 0xa4, 0x84, 0x82, 0x5a, 0xf7, 0x20, 0x05, 0x21,
	0x62, 0x3d, 0x78, 0xf2, 0xa2, 0x1e, 0x5a, 0x68, 0x55, 0x52, 0x22, 0x78, 0x92, 0x4d, 0x79, 0x94,
	0xc0, 0x26, 0x59, 0x77, 0x13, 0x48, 0x7e, 0x8f, 0x7f, 0x54, 0x12, 0x93, 0x10, 0x15, 0xbd, 0xbd,
	0x99, 0x9d, 0x9d, 0x9d, 0xd9, 0x07, 0x63, 0xcc, 0xde, 0xa4, 0x7f, 0x89, 0x99, 0x23, 0x55, 0x9c,
	0xc4, 0xf4, 0x60, 0xaf, 0xe4, 0x0e, 0x33, 0x1e, 0x4a, 0x81, 0xec, 0x14, 0xcc, 0x65, 0xe0, 0xe2,
	0x7b, 0x8a, 0x3a, 0xa1, 0x14, 0x7a, 0x11, 0x0f, 0xd1, 0x26, 0x33, 0x32, 0x37, 0xdd, 0x72, 0x66,
	0x67, 0x30, 0x2c, 0x04, 0x52, 0xe4, 0x74, 0x02, 0x83, 0x10, 0xb5, 0xde, 0xd7, 0x82, 0x0a, 0xb1,
	0x0f, 0x02, 0xd6, 0x3d, 0x17, 0xbb, 0x54, 0xf0, 0x04, 0x6b, 0x2f, 0x1b, 0x86, 0x51, 0x1a, 0xfa,
	0xa8, 0xb4, 0x4d, 0x66, 0xc6, 0xdc, 0x70, 0x6b, 0x48, 0xef, 0x60, 0x14, 0x4b, 0x54, 0x3c, 0x89,
	0x95, 0xdd, 0x9d, 0x91, 0xf9, 0x78, 0x71, 0xee, 0xb4, 0x22, 0x39, 0x3f, 0xad, 0x9c, 0xa7, 0x4a,
	0xed, 0x36, 0xf7, 0xd8, 0x15, 0x8c, 0x6a, 0x96, 0x8e, 0xa0, 0xf7, 0xbc, 0xf6, 0xb6, 0x56, 0x87,
	0x9a, 0xd0, 0xdf, 0xac, 0x1e, 0xbd, 0xad, 0x45, 0xe8, 0x10, 0x8c, 0x8d, 0xb7, 0xb6, 0xba, 0xc5,
	0xf0, 0xb0, 0x7a, 0xb1, 0x0c, 0x76, 0x01, 0x87, 0x2d, 0x67, 0x2d, 0xe3, 0x48, 0x63, 0x51, 0x49,
	0xa1, 0x4e, 0x45, 0x52, 0x56, 0x32, 0xdc, 0x0a, 0x2d, 0x6e, 0xa1, 0xbb, 0x0c, 0xe8, 0x0d, 0xf4,
	0xb7, 0x3c, 0x5f, 0x06, 0x74, 0xf2, 0x2d, 0x60, 0xf3, 0x61, 0xd3, 0xa3, 0x5f, 0xbc, 0x14, 0x39,
	0xeb, 0x2c, 0x5e, 0xc1, 0x6c, 0xde, 0xa2, 0xeb, 0x36, 0x38, 0xfe, 0xb7, 0xea, 0xf4, 0xe4, 0xaf,
	0xe3, 0xaf, 0xbc, 0xac, 0xe3, 0x0f, 0xca, 0x25, 0x5e, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0x8c,
	0x44, 0x78, 0x4e, 0xd6, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HiClient is the client API for Hi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HiClient interface {
	SayHi(ctx context.Context, in *HiRequest, opts ...grpc.CallOption) (*HiReply, error)
}

type hiClient struct {
	cc *grpc.ClientConn
}

func NewHiClient(cc *grpc.ClientConn) HiClient {
	return &hiClient{cc}
}

func (c *hiClient) SayHi(ctx context.Context, in *HiRequest, opts ...grpc.CallOption) (*HiReply, error) {
	out := new(HiReply)
	err := c.cc.Invoke(ctx, "/grpcexample.Hi/SayHi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HiServer is the server API for Hi service.
type HiServer interface {
	SayHi(context.Context, *HiRequest) (*HiReply, error)
}

// UnimplementedHiServer can be embedded to have forward compatible implementations.
type UnimplementedHiServer struct {
}

func (*UnimplementedHiServer) SayHi(ctx context.Context, req *HiRequest) (*HiReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHi not implemented")
}

func RegisterHiServer(s *grpc.Server, srv HiServer) {
	s.RegisterService(&_Hi_serviceDesc, srv)
}

func _Hi_SayHi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HiServer).SayHi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcexample.Hi/SayHi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HiServer).SayHi(ctx, req.(*HiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcexample.Hi",
	HandlerType: (*HiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHi",
			Handler:    _Hi_SayHi_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ex_pb/ex.proto",
}

// CalculateClient is the client API for Calculate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalculateClient interface {
	Calculate(ctx context.Context, in *CalculateRequest, opts ...grpc.CallOption) (*CalculateResponse, error)
}

type calculateClient struct {
	cc *grpc.ClientConn
}

func NewCalculateClient(cc *grpc.ClientConn) CalculateClient {
	return &calculateClient{cc}
}

func (c *calculateClient) Calculate(ctx context.Context, in *CalculateRequest, opts ...grpc.CallOption) (*CalculateResponse, error) {
	out := new(CalculateResponse)
	err := c.cc.Invoke(ctx, "/grpcexample.Calculate/Calculate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalculateServer is the server API for Calculate service.
type CalculateServer interface {
	Calculate(context.Context, *CalculateRequest) (*CalculateResponse, error)
}

// UnimplementedCalculateServer can be embedded to have forward compatible implementations.
type UnimplementedCalculateServer struct {
}

func (*UnimplementedCalculateServer) Calculate(ctx context.Context, req *CalculateRequest) (*CalculateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Calculate not implemented")
}

func RegisterCalculateServer(s *grpc.Server, srv CalculateServer) {
	s.RegisterService(&_Calculate_serviceDesc, srv)
}

func _Calculate_Calculate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculateServer).Calculate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcexample.Calculate/Calculate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculateServer).Calculate(ctx, req.(*CalculateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Calculate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcexample.Calculate",
	HandlerType: (*CalculateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calculate",
			Handler:    _Calculate_Calculate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ex_pb/ex.proto",
}
